### ISSUE TITLE
decompile script ".luc"

### ISSUE THREAD

**Issue by KITT3000** [jjdredd/ljd#3]
I have a script compiled in LuaJIT (newer version than 2.0), and I wanted to decompile it with "LJD," but I have a problem. I have Linux Mint 17 and installed Python 3.4  and tried to decompile the script, but I have this error:

> kamil@AsusK53SV ~/ljd $ python3 main.py SkidSteerFix.luc
> Traceback (most recent call last):
>   File "main.py", line 123, in <module>
>     retval = main()
>   File "main.py", line 85, in main
>     ast = ljd.ast.builder.build(prototype)
>   File "/home/kamil/ljd/ljd/ast/builder.py", line 28, in build
>     return _build_function_definition(prototype)
>   File "/home/kamil/ljd/ljd/ast/builder.py", line 49, in _build_function_definition
>     node.statements.contents = _build_function_blocks(state, instructions)
>   File "/home/kamil/ljd/ljd/ast/builder.py", line 71, in _build_function_blocks
>     _establish_warps(state, instructions)
>   File "/home/kamil/ljd/ljd/ast/builder.py", line 175, in _establish_warps
>     block.warp, shift = _build_warp(state, block.last_address, warp)
>   File "/home/kamil/ljd/ljd/ast/builder.py", line 198, in _build_warp
>     return _build_numeric_loop_warp(state, last_addr, last)
>   File "/home/kamil/ljd/ljd/ast/builder.py", line 318, in _build_numeric_loop_warp
>     warp.body = state._warp_in_block(destination)
>   File "/home/kamil/ljd/ljd/ast/builder.py", line 22, in _warp_in_block
>     block = self.block_starts[addr]
> KeyError: -32723

**Comment by jjdredd** [comment]
Can you specify the bytecode version (luajit version that was used to compile the script) and the branch of ljd you were using.

**Comment by KITT3000** [comment]
The script was compiled by Giants Software, and I used ljd-bugfix (downloaded today). Using LuaJIT 2.1, manages to get the bytecode.

**Comment by jjdredd** [comment]
So, have you tried using branch 'ljv2.1'?

**Comment by KITT3000** [comment]
Yes, I have not found a newer version. Unless there is some other way to get the bytecode and decompile script.

In previous versions of the game used the "unluac" Giants changed the way we now compile scripts and do not really know how to decompile the files.

ljv2.1:

> Traceback (most recent call last):
>   File "main.py", line 28, in <module>
>     import ljd.rawdump.parser
> ImportError: No module named 'ljd.rawdump'

**Comment by jjdredd** [comment]
make sure you're running the script from the directory where main.py and ljd dir are located

**Comment by KITT3000** [comment]
Incorrectly copied files to the new folder :p

But now there is only one error (ljd-bugfix downloaded again and now it is the same error):

> Invalid magic, not a LuaJIT format
> Failed to read raw-dump header

**Comment by jjdredd** [comment]
bugfix branch probably doesn't suit you. Can you send the file?

**Comment by KITT3000** [comment]
original - http://www10.zippyshare.com/v/v2lT73Og/file.html
bytecode - http://www10.zippyshare.com/v/JZY1o4FQ/file.html

**Comment by jjdredd** [comment]
it works just fine on branch ljv2.1:

``` lua
local modFilename, isMod, isDlc, dlcsDirectoryIndex = Utils.removeModDirectory(g_currentModDirectory)

if not _G.g_jcbSkidSteerFix and isDlc and g_currentModName == "pdlc_jcbPack" then
    _G.g_jcbSkidSteerFix = true
    local orderId = StoreItemsUtil.storeCategories.teleLoaders.orderId + 0.1
    local name = "skidSteers"
    StoreItemsUtil.storeCategories[name] = {
        orderId = orderId,
        name = name,
        title = g_i18n:getText(name),
        image = g_currentModDirectory .. "store_jcb260eco.png"
    }

    Vehicle.registerJointType("skidSteer")
end

return 

```

**Comment by KITT3000** [comment]
Thanks, but what else am I doing wrong?

**Comment by jjdredd** [comment]
git clone ...
cd ljd
git checkout ljv2.1
python3 main.py /path/to/file.luc

**Comment by KITT3000** [comment]
Ok, now it works. Thank you very much for your help.
